name: Build app

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: Bygg app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v4
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # ratchet:actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - name: Npm install build
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Npm build
        run: npm run build
